package com.sanisamoj.database.mongodb

enum class Fields(val title: String) {
    Id(title = "_id"),
    Bio(title = "bio"),
    Nick(title = "nick"),
    Name(title = "name"),
    Date(title = "date"),
    Type(title = "type"),
    Email(title = "email"),
    Phone(title = "phone"),
    Status(title = "status"),
    UserId(title = "userId"),
    EventId(title = "eventId"),
    Address(title = "address"),
    ParentId(title = "parentId"),
    Username(title = "username"),
    AccountId(title = "accountId"),
    Presences(title = "presences"),
    CreatedAt(title = "createdAt"),
    PromoterId(title = "promoterId"),
    FollowerIds(title = "followerIds"),
    Description(title = "description"),
    AnswersCount(title = "answersCount"),
    FollowingIds(title = "followingIds"),
    ImageProfile(title = "imageProfile"),
    AccountStatus(title = "accountStatus"),
    ValidationCode(title = "validationCode"),
    AccountIsPublic(title = "accountIsPublic"),
    PendingSentRequests(title = "pendingSentRequests"),
    PendingFollowRequests(title = "pendingFollowRequests"),
}